Windows Visual Studio support. WIP

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,6 +15,7 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    
       - uses: actions/checkout@v3
 
       - name: install cpplint
@@ -31,7 +32,7 @@ jobs:
         run: python3 ${{github.workspace}}/scripts/install_deps.py --mode 2
 
       - name: Configure Engine CMake
-        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DRB2D_BUILD_TESTS=ON
+        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DRB2D_BUILD_TESTS=ON -DRB2D_BUILD_EDITOR=ON
 
       - name: Engine Build
         run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target robot2D-editor --target run_all_tests -- -j 2
@@ -53,4 +54,54 @@ jobs:
         uses: actions/upload-artifact@v2
         with:
             name: linux-assets
+            path: ${{github.workspace}}/linter
+            
+  build-windows:
+    env: 
+      glfw3_DIR: 'C:\Program Files\GLFW\lib\cmake\glfw3'
+      spdlog_DIR: 'C:\Program Files\spdlog\lib\cmake\spdlog'      
+    runs-on: windows-latest
+
+    steps:
+    
+      - uses: actions/checkout@v3
+
+      - name: install cpplint
+        run: python -m pip install cpplint
+        shell: cmd
+
+      - name: Create linter folder
+        run: mkdir ${{github.workspace}}\linter
+        shell: cmd
+        
+      - name: Install dependencies
+        run: python3 ${{github.workspace}}/scripts/install_deps.py --mode 2 --wincompiler 2 --winvsversion 2
+        shell: cmd
+        
+      - name: Configure Engine CMake
+        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DRB2D_BUILD_TESTS=ON -DRB2D_BUILD_EDITOR=OFF
+        shell: cmd
+        
+      - name: Engine Build
+        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
+        shell: cmd
+        
+      - name: Run Tests
+        run: ctest --output-junit engine_tests.xml --output-on-failure --test-dir ${{github.workspace}}/build/tests
+        continue-on-error: true
+        shell: cmd
+        
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: tests-windows           # Name of the check run which will be created
+          path: build/tests/*.xml    # Path to test results
+          reporter: java-junit        # Format of test results
+        continue-on-error: true  	
+        
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v2
+        with:
+            name: windows-assets
             path: ${{github.workspace}}/linter
