Try testing on CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,6 +36,17 @@ jobs:
       - name: Engine Build
         run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
 
+      - name: Run Tests
+        run: ctest test --output-junit engine_tests.xml --output-on-failure
+      
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Engine Tests            # Name of the check run which will be created
+          path: tests/*.xml    # Path to test results
+          reporter: jest-junit        # Format of test results   	
+
       - name: Upload artifacts
         uses: actions/upload-artifact@v2
         with:
